'use client'

import { Header } from '@/components/layout/header'

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <Header />
      
      <main className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
        <div className="mb-4 text-sm text-muted-foreground">
          Last Updated: January 5, 2026
        </div>
        <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
        
        <div className="prose dark:prose-invert max-w-none space-y-6">
          <section>
            <h2 className="text-2xl font-semibold mb-4">Agreement to Terms</h2>
            <p>By accessing and using GetHired, you represent and warrant that you are at least 18 years of age. By accessing and using GetHired, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Use License</h2>
            <p>Permission is granted to temporarily download one copy of the materials (information or software) on GetHired for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not: modify the materials, copy the materials, use the materials for any commercial purpose or for any public display, attempt to decompile or reverse engineer any software contained on the service, transfer the materials to another person, or replicate the materials on any other server.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Refund Policy</h2>
            <p>Since GetHired offers non-tangible, irrevocable digital goods, we do not provide refunds after the product is purchased, which you acknowledge prior to purchasing any product on the website. Please make sure that you&apos;ve carefully read the service description before making a purchase.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">AI-Generated Content Disclaimer</h2>
            <p>Our Service uses Artificial Intelligence (AI) to generate and improve resume content. While we strive for accuracy, AI can produce incorrect, misleading, or offensive information (&quot;hallucinations&quot;). You acknowledge that you are solely responsible for reviewing, editing, and verifying the final resume content before using it for any purpose. GetHired is not liable for any errors, inaccuracies, or hallucinations generated by the AI, or for any consequences resulting from the use of such content, including but not limited to job application rejections, employment terminations, or legal disputes.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">No Guarantee of Employment</h2>
            <p>GetHired is a tool for creating and improving resume documents. We do not guarantee that using our Service will result in job interviews, job offers, or employment. We are not a recruitment agency, and we do not provide job placement services. Your ability to obtain employment depends on many factors beyond our control, including your qualifications, experience, market conditions, and employer discretion.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Disclaimer</h2>
            <p>The materials on GetHired are provided on an &apos;as is&apos; basis. GetHired makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Limitations of Liability</h2>
            <p>In no event shall GetHired or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on GetHired.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Accuracy of Materials</h2>
            <p>The materials appearing on GetHired could include technical, typographical, or photographic errors. GetHired does not warrant that any of the materials on its website are accurate, complete, or current. GetHired may make changes to the materials contained on its website at any time without notice.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Links</h2>
            <p>GetHired has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by GetHired of the site. Use of any such linked website is at the user&apos;s own risk.</p>
          </section>
        </div>
      </main>
    </div>
  )
}
